#!/bin/bash

UMBRAL=0.5  

USO=$(df / | grep / | awk '{print $5}' | tr -d '%' | tr ',' '.')

if (( $(echo "$USO > $UMBRAL" | bc -l) )); then
	  echo "AVISO: UMBRAL SUPERADO! Uso del disco: $USO%"
fi



